### ISSUE TITLE
how train other models

### ISSUE THREAD

**Issue by jeansely** [JihongJu/keras-fcn#12]
Hi,
for train my model ,i used your code (voc_generator.py , train.py,  init_args.yml). but my output model has output shape (1,121,121,21), where should be change in the files, I've tested all possible states in 'init_args.yml'

the error is ;
Traceback (most recent call last):
  File "C:\cnn\inceptionV4\keras-fcn\keras-fcn-master\voc2011\train.py", line 121, in <module>
    callbacks=[lr_reducer, early_stopper, csv_logger])
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\keras\legacy\interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\keras\engine\training.py", line 1902, in fit_generator
    class_weight=class_weight)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\keras\engine\training.py", line 1636, in train_on_batch
    check_batch_axis=True)
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\keras\engine\training.py", line 1315, in _standardize_user_data
    exception_prefix='target')
  File "C:\Program Files\python3.5\python-3.5.3.amd64\lib\site-packages\keras\engine\training.py", line 139, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected decoder to have shape (1, 121, 121, 21) but got array with shape (1, 500, 500, 21)

**Comment by JihongJu** [comment]
@jeansely Are you using FCN? So the current version of FCN only works with VGG16. If you want to use the other models, for example InceptionV4. You need to modify the codes accordingly. Basically, you need to write a BaseNet (which is IncaptionV4 in this case) and provide it to the FCN model.
