### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by biyoner** [JihongJu/keras-fcn#34]
Hi ,thanks for your code!
I have a problem. Can you help me ?
---------------------------------------------------------------------------------------------------------------------------------------------
Loading weights...
Epoch 1/100
Traceback (most recent call last):
  File "/home/ilab/biyoner/sementic_seg/keras-fcn/voc2011/train.py", line 88, in <module>
    callbacks=[early_stopper, csv_logger, checkpointer, nan_terminator])
  File "/home/ilab/biyoner/keras/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/ilab/biyoner/keras/local/lib/python2.7/site-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/home/ilab/biyoner/keras/local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 557, in get
    six.raise_from(StopIteration(e), e)
  File "/home/ilab/biyoner/keras/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
StopIteration

Process finished with exit code 1

Thanks.

**Comment by kangmengmeng** [comment]
@biyoner I have the same problem,could you tell me how do you solved it?

**Comment by kangmengmeng** [comment]
可能是keras的版本问题，我把keras从2.2.4降到2.0.8之后没有报错了。
